/*
|--------------------------------------------|
         ⚡️ Generated by Agentsmith ⚡️
      ⚠️ Do not edit this file directly ⚠️
|--------------------------------------------|
*/
export type PromptVariables__make_a_full_fledged_application__0_0_1 = never;
export type PromptConfig__make_a_full_fledged_application__0_0_1 = {
  models: ['openrouter/auto'];
  temperature: number;
};
export type PromptVersion__make_a_full_fledged_application__0_0_1 = {
  version: '0.0.1';
  config: PromptConfig__make_a_full_fledged_application__0_0_1;
  variables: PromptVariables__make_a_full_fledged_application__0_0_1;
  content: string;
};
export type Prompt__make_a_full_fledged_application = {
  name: 'Make a full fledged application ';
  slug: 'make-a-full-fledged-application';
  versions: {
    latest: never;
    '0.0.1': PromptVersion__make_a_full_fledged_application__0_0_1;
  };
};
export type Globals = {};
export type Agency = {
  prompts: {
    'make-a-full-fledged-application': Prompt__make_a_full_fledged_application;
  };
  globals: Globals;
};
